### ISSUE TITLE
some questions about paper

### ISSUE THREAD

**Issue by zhujiawen1994** [Microsoft/singleshotpose#25]
Hello, sir, I am sorry to bother you again. But I have a few questions about paper.
1. Accurately speaking, the whole process did two things, object detection and object 6D pose estimation. As for the object detection part, I don't quite understand how it is done. What method is used to detect the object in the paper? Is it based on the confidence value? How do the four detection points representing objects in Figure 1(c) be obtained?
2. Regarding the output part of the network, the input image is divided into S*S mesh after the convolution network, and finally the target value bit D-dimensional vector is output. Does each cell correspond to to a D dimensional vector? Or just the cell containing point information corresponds to a D dimensional vector?
3. Regarding the confidence function c(X), DT(x) represents the distance between the projection point and the ground truth point. How do you get it? By depth information?
4.Regarding the class probability, there is not much explanation in the paper. Could you please explain it briefly?

**Comment by btekin** [comment]
Here are the answers to your questions:

1. We are not directly interested in detecting the object with a tight 2D rectangular bounding box as in standard object detection papers such as YOLO, SSD, Faster R-CNN. Instead, we are interested in estimating some 2D keypoints on the object with a single shot network so that these keypoints can then be used to estimate the 6D pose of the object. These keypoints are chosen as the projection of the centroid and 3D bounding box of the provided 3D object model. The points in Fig. 1(c) represent the centroid of the object. Please, see Section 3.1, 3.2, and the references therein for all the detailed explanations.

2. Only the cell corresponding to the centroid of the object has the D dimensional vector containing target values. In the output grid, every cell predicts a D-dimensional vector and low-confidence predictions are eliminated at test time.

3. DT(x) represents the distance between the predicted 2D point and ground-truth target 2D point. Therefore, while computing DT(x), depth information is not used at all. 

4. In a standard manner, the prediction is a vector of probability values between 0 and 1 for each different object category in the dataset. The target value for the class of the object is a vector with all '0's except one '1' and the location of '1' in the vector corresponds to the class label of the object. We use cross-entropy loss between the prediction and target to classify the object.

**Comment by zhujiawen1994** [comment]
I see，thank you for your detailed answer.
I know what DT(x) means, but how  get it?

**Comment by btekin** [comment]
As explained in Section 3.1, the distance DT (x) is defined as the 2D Euclidean distance of the ground-truth 2D point and predicted 2D point in the image space. We apply the confidence function to all the control points and calculate the mean value and assign it as the confidence.

**Comment by zhujiawen1994** [comment]
Ok, I see. By running valid.py, I get the rotation matrix R_pr and the translation vector t_pr. Finally, if I want to get the final 6D pose of the object (represented by 21 numbers), I also need to know the camera coordinate system and the reference 3D bounding box of the object model. Is right?
Or could you please recommend some links to the reference about estimating 6D pose of the object in terms of a rotation matrix and the translation vector.
Best wishes!

**Comment by btekin** [comment]
6D pose of the object is **already** defined as the rotation matrix and translation vector. This is the definition of the 6D pose estimation problem, its aim is to find the rotation matrix and translation vector of the objects. 21 numbers just contain information about the class and range (extent) of the object, and the positions of 9 2D control points as I also explained in #19, they are not the ultimate output of the method and do not directly define the 6D pose of the object. Given the 2D predictions of 9 control points (also knowing the intrinsic camera matrix and reference 3D bounding box), we apply perspective-n-point (PnP) algorithm to estimate 6D pose of the object in terms of a rotation matrix and the translation vector. 

I could advise you to look at the following early survey for a general understanding of the problem (especially, the first chapter): http://icwww.epfl.ch/~lepetit/papers/lepetit_ftcgv05.pdf and some online preliminary information about perspective-n-point (PnP) method. If you are interested, you can also learn more about the object pose estimation and state-of-the-art in papers such as Hinterstoisser et al, ACCV'12, Brachmann et al., ECCV'14, Brachmann et al. CVPR'16, Rad & Lepetit, ICCV'17, Kehl et al. ICCV'17 (you can find more detailed references in our paper). 

P.S. As this is not an issue for the code of our method but general questions on object pose estimation problem, maybe it's better to discuss about these on email rather than here. Thanks for your interest in our study!
