### ISSUE TITLE
Why the occupied GPU memory keep increasing and finally get GPU memory error?

### ISSUE THREAD

**Issue by shanyuhu** [Microsoft/singleshotpose#26]

**Comment by btekin** [comment]
Which GPU model do you use and how much GPU memory do you have? On Pascal TITAN X with 12 GB memory, there aren't any memory problems and the occupied space is around 8GB with a batch size of 32. If you have memory problems you can maybe try decreasing the batch size.

**Comment by shanyuhu** [comment]
@btekin , thanks for your answering. I use one Tesla K80 with 12G memory and train with the default setting with batch=32. Initially, the occupied memory is around 11G. After around 70 epoch, the occpied memory increases to out of the memory of 12G and the training process stoped.

**Comment by btekin** [comment]
It might be due to the multi-scale training. We change the input resolution during training randomly and with the increasing resolution of input images the activation maps are taking up more space. But still 12 GB of memory should be sufficient enough. Did you check if some other process is already running on GPU and taking up space. If so, you can try killing that process and run again. You might also find the discussion in #12 helpful to resolve your memory problem.

**Comment by shanyuhu** [comment]
Thanks, it seems that I meet the same issue with #12. I will also check the code to figure out why this happens, since it is fine with batch 32 in TITAN X.
