### ISSUE TITLE
What's the difference between LINEMOD and OCCLUSION dataset?

### ISSUE THREAD

**Issue by kevinkit** [Microsoft/singleshotpose#34]
The paper states that the architecture was tested on the LINEMOD and the OCCLUSION dataset. I was able to download the LINEMOD dataset, however I was unable to find OCCLUSION to see what the differences are.

It looks like they are basically the same with different annotations ? Can somebody please give me some hints for that? 

Thanks in adavance

**Comment by SergioRAgostinho** [comment]
The Occlusion Dataset is a reannotation of the benchvise segment of the LINEMOD dataset. All objects are now annotated instead of simply the benchvise. You're likely to find more info here https://hci.iwr.uni-heidelberg.de/vislearn/iccv2015-occlusion-challenge/

Here's a direct link to the [dataset](https://cloudstore.zih.tu-dresden.de/index.php/s/a65ec05fedd4890ae8ced82dfcf92ad8/download), extracted from the page I previously linked.

**Comment by chenyu36** [comment]
I had success in creating labels (i.e. the ground truth) for custom objects, but not sure how to create the lables_occlusion similar to those in LINEMOD dataset. I am using Unity game engine to create the ground truth.
@btekin Could you provide detail instructions on how to create labels for occlusion for multi obj pose estimation?

**Comment by scp10086** [comment]
Help! I want to create a 3D model of my cup with intel RealSense SR300. Is there any 3D scan software (Free and useful) which support that device?

**Comment by satpalsr** [comment]
Hey @chenyu36, did you figure out creating labels for the occlusion dataset. I am having problem specifically with different rotation matrix in occlusion dataset for each of the object.
