### ISSUE TITLE
some question about multi-obj-pose

### ISSUE THREAD

**Issue by AceCoooool** [microsoft/singleshotpose#58]
Thank you for your work @btekin , and I have some questions about the multi-object-pose-estimation

1. The output of this part is `1xh//13xw//13x160`: why using channel=160? (9x2+1+C, should be 9x2+1+13=32) 
2. In the valid phase, it's "strange" to think the largest confidence corresponding to the object we want --- For example, in the ape we use the largest confidence, and in the cat we also use the largest onfidence. However, the largest confidence may corresponding to other objects.   (it's only possible when the test image we have already seen in the training phase)
```
# If the prediction has the highest confidence, choose it as our prediction
for j in range(len(boxes)):
    if (boxes[j][18] > best_conf_est) and (boxes[j][20] == int(truths[k][0])):
        best_conf_est = boxes[j][18]
        box_pr = boxes[j]
        bb2d_gt = get_2d_bb(box_gt[:18], output.size(3))
        bb2d_pr = get_2d_bb(box_pr[:18], output.size(3))
        iou = bbox_iou(bb2d_gt, bb2d_pr)
        match = corner_confidence9(box_gt[:18], torch.FloatTensor(boxes[j][:18]))
```

**Comment by anuar12** [comment]
1. you forgot about the number of anchor box predictors, they use 5. So it should be (9*2+1+13)*5.
I think you can change it depending on variability of sizes of your bboxes or depending on how dense your scenes are.

**Comment by btekin** [comment]
1. Thanks for your reply @anuar12. You should also account for the anchor boxes.
	
2. We need indeed to see the category of a test object during the training phase as the approach is a fully-supervised one and we do not consider the zero-shot learning problem. This part is used during evaluation to measure pose estimation accuracy for the object classes _which we know to be a part of the Occlusion dataset_. However, at the same time, this approach might not ideally work when there are multiple instances of the same object (which is not the case for the Occlusion dataset). In that case, a thresholding-based approach instead of choosing the highest confidence would make more sense.

**Comment by chenyu36** [comment]
> However, at the same time, this approach might not ideally work when there are multiple instances of the same object (which is not the case for the Occlusion dataset). In that case, a thresholding-based approach instead of choosing the highest confidence would make more sense.
>
@btekin 
Could you elaborate on the thresholding-based approach for multiple instances of the same object?
I tried to sort the confidence level of the bbox, but in my case, it turns out that the top 2 bbox could go to the same object sometimes.

**Comment by btekin** [comment]
It would make sense to have a reasonable threshold and accept detections above this threshold instead of choosing top-K predictions. In this case, there might be multiple detections for the same object. As a solution, non-maxima suppression could be used to eliminate those detections with lower confidence.
