### ISSUE TITLE
Strange results: 0% accuracy, unexpected 3D bounding box

### ISSUE THREAD

**Issue by aurora-ramalho** [Microsoft/singleshotpose#61]
I'm having some trouble when applying your code to a different dataset.
When I run valid.py and save the results, the returned accuracy is 0% and the errors are really high. The saved results return the following for two random images I picked (green: real, blue: predicted):

![img1000](https://user-images.githubusercontent.com/46962751/51847978-ac630780-2314-11e9-9342-050175484b13.png)
![img5](https://user-images.githubusercontent.com/46962751/51847979-ac630780-2314-11e9-8c68-159ab30309cd.png)

At first, I thought it was a scaling problem, as mentioned in other questions, but the scale seems correct. Either way, the predicted bounding boxes don't have the correct shape.
Any idea why this is happening?

Thank you very much for your time

**Comment by Youyi7** [comment]
Could you please tell me how to visualize the results?

**Comment by btekin** [comment]
I would check first if the 2D predictions (before PnP) are accurate by visualizing them. Could you maybe tell what the mean corner error is before PnP? I suspect this might be a similar problem with #73. My guess is that the problem comes from the PnP stage. To fix that, I would make sure if the 3D point coordinates are in an appropriate unit (e.g. mm or m) and if the intrinsic matrix is correct. I would maybe suggest to follow the same units for the LINEMOD dataset. You could also find the discussion in #68 useful to check if your .ply file is correctly formed.

**Comment by btekin** [comment]
Please also check issue #49, it might also be relevant for your problem.

**Comment by btekin** [comment]
Closing the issue, please feel free to reopen it if you would like to continue discussing.
