### ISSUE TITLE
Results different from what stated in paper

### ISSUE THREAD

**Issue by nfanaa19940122** [Microsoft/singleshotpose#71]
When I tested the network using the weights you provided in the zip file, the results are a bit different from what stated in the paper. 
For example, the results for ape is  92.10%(2D projection error) and 21.62%(ADD), while my results are 94.48% (2D projection error) and 28.00%(ADD)
"
Acc using 5 px 2D Projection = 94.48%
Acc using 10% threshold - 0.0103 vx 3D Transformation = 28.00%
"
I'm a little confused about this...

Also, could you please provide the trained model weights for "phone"? I cannot find it in the zip file...
Thank you!!!

**Comment by btekin** [comment]
Hello, thanks for your interest in our work. Before code release, I had to retrain all the models for single object pose estimation after paper submission, as I couldn't find the models used in the paper. The retrained models that we provide, as you also observed, do not change much from the initial results that we got. Here for example, the reprojection error with the retrained model is even higher by about 2%. 
I couldn't upload the the model at the code release because of my personal cloud storage quota. But, in any case, the training shouldn't take a very long time, it should be possible to retrain the model with the provided training code and ImageNet initialization weights in a short time.

**Comment by nfanaa19940122** [comment]
> Hello, thanks for your interest in our work. Before code release, I had to retrain all the models for single object pose estimation after paper submission, as I couldn't find the models used in the paper. The retrained models that we provide, as you also observed, do not change much from the initial results that we got. Here for example, the reprojection error with the retrained model is even higher by about 2%.
> I couldn't upload the model for the phone object at code release because of my personal cloud storage quota. But, in any case, the training shouldn't take a very long time, it should be possible to retrain the model with the provided training code and ImageNet initialization weights in a short time.

Thank you for your kind reply! Got it ～
