### ISSUE TITLE
What is wrong with my model? + summary & solutions to F.A.Q

### ISSUE THREAD

**Issue by jgcbrouns** [microsoft/singleshotpose#75]
Hi everyone!

I was already having a discussions about my issues in [issue-68](https://github.com/Microsoft/singleshotpose/issues/68), but decided to open a separate ticket anyway for completeness towards other people. As of now. I am clueless what is wrong with my model. My workflow and solved issues are as follows:

- Using Unity3D, I created a data-set with around 240 training-images and 60 test-images for a custom model: a cube with 4 different colors (for testing). 

I came across multiple issues regarding the following:
- I set my camera calibration intrinsic parameters as follows:
```
    K = np.zeros((3, 3), dtype='float64')
    K[0, 0], K[0, 2] = 320, 320
    K[1, 1], K[1, 2] = 320, 240
    K[2, 2] = 1.
```
Annotated labels are created automatically in Unity3D of which I expect there to be no camera distortion (for the intrinsic camera calibration). The original author's of the LINEMOD dataset use a Kinect camera that does have such a camera distortion. This internal camera calibration is necessary for among others the PnP-algorithm. 

- Initially, I had many problems with creating my .PLY files:
    - Scaling them into meters. I think I managed this my .PLY file [here](https://www.succes.network/singleshotpose/cube_rotated_scaled.ply): 
    - Apparently models have to be centered at their volumetric point of mass at the origin (0,0,0). I centered my objects at the bottom-surface, giving them an unwanted offset.
- Bounding-box coordinates need to be in a specific order in their respective annotated label file. If this is not the case, the bounding-box that gets generated form the .PLY file and predictions from singleshotpose will be distorted completely. There are multiple issues on Github about this (among which [issue-49](https://github.com/Microsoft/singleshotpose/issues/49)
  - Correct order of boundingbox coordinates in label file (green border):
![39](https://user-images.githubusercontent.com/8687567/55228009-4530d900-5219-11e9-950e-fb2eca7be397.png)
   - Incorrect order of boundingbox coordinates in label file:
![Capture](https://user-images.githubusercontent.com/8687567/55227982-30ecdc00-5219-11e9-850e-9844d272b2dc.PNG)

Find here, an example of an [image](https://www.succes.network/singleshotpose/2.png) and a [label](https://www.succes.network/singleshotpose/2.txt) file from my trainings-set.

### HOWEVER.

I am still not obtaining correct results and I am unsure about how long to train my models for. In the implementation 700epochs are stated, yet if I train for 4000 epochs, my results are still not good:

![after4000+epochs](https://user-images.githubusercontent.com/8687567/55227956-174b9480-5219-11e9-8ae1-39562dffafb4.png)

**How many epochs should a new object be trained for?** 
**NOTE:** I am using benchvise/init.weights as my initial weights for my new model of the custom data-set.
This while **my loss function goes down properly, but my accuracy measurements stay at 0%:**

![4000+epochs_terminal](https://user-images.githubusercontent.com/8687567/55227949-10bd1d00-5219-11e9-839b-fd9fb474e4e5.PNG)

**Could there still be a problem with how I created the annotation files, camera intrinsic parameters or .PLY model. Or could there be another problem that I am not considering?**

@btekin Would it be an idea to add a F.A.Q section to the README, using my findings? I think the section about training on a custom data-set could use a lot more elaboration.

Moreover, I am curious as to what people are doing with singleshotpose. Anyone experimenting with some interesting use-cases?

Many thanks for anyone that can help!

**Comment by jgcbrouns** [comment]
I managed to get my "Acc using x vx 3D transformation up to 20 - 30%" using a more appropriate diameter in the .data file. I calculated this diameter using a piece of code that pair-wise compares all vertices and takes the pair with the greatest distance. 

Unfortunately I am not able to get any accuracy at the other 2 metrics (Acc using 5px 2D projection and Acc using 5 cm 5 degree metric). It seems that the model is unable to learn from my data? Might the data be too monotonous? If so I would expect to at least see some accuracy metrics go up (because the model would just over-fit).

**Comment by jgcbrouns** [comment]
Too bad that nobody seems to be able (or willing) to help. I have a little update:

  - Instead of 240 training-images, I now used **4000 training-images.**
  - I also added random-background colors and added more colors to the cube (since I thought that the model was unable to learn about my cube object due to insuccifient features in texture).

My accuracy after 1000 epochs is:
![56492513_2003465433296047_4332711249553915904_n](https://user-images.githubusercontent.com/8687567/55670595-c4ac5100-5886-11e9-9b5c-eb13dfab92be.png)

![56956445_416356655794769_8403792676486381568_n](https://user-images.githubusercontent.com/8687567/55670582-ab0b0980-5886-11e9-88e1-0cf0e6b81769.png)


What I find weird is that LINEMOD has only ±200 images per class for training (and ±1000 for testing). Hence, their training-set is very small, yet @btekin was able to reach high accuracy >90%. @btekin, I would love to hear your input about this. Is this due to pre-training? Can you tell us a bit more about how long your pretraining took and what parameters you used in your training/test set?

**Sidenote:**
I do believe that the trainings-images of LINEMOD are selected in such a way that together they represent a good 3D presentation of an object. In other words, every image in the trainigsset features the object from a unique POV (unique camera angle, position etc). Could this be of influence on why my model cannot seem to learn with only 240 images? On the other hand, I do expect the model to at least learn something with a small datset, when increasing the amount of epochs to train for; the model would overfit but still should learn and return high accuracies on the training-set.

Any thoughts?

**Comment by btekin** [comment]
Hello, thanks for your interest in our code and sorry for the late reply, I didn't have the time to reply as I had to deal with my other work related projects. 

We follow the same training/test splits with earlier work, e.g. that of the BB8 paper by Rad & Lepetit, ICCV'17. Indeed, the training examples are sampled such that they cover a wide variety of viewpoints around the object. Having a more representative training set should, in principle, increase the accuracy on test examples. 

Instead of using initialization weights for another object, you could also pretrain the network on the same object by setting the regularization parameter for the confidence loss to zero, as explained in the readme file. See also the discussion in the paper and in #79 why such pretraining could be useful.

About your findings: We already mention what order should be used for the keypoints in this [link](https://github.com/Microsoft/singleshotpose/blob/master/label_file_creation.md) along with a step-by-step guide and this was also discussed in the duplicate issue #68. Custom datasets have different camera intrinsics matrix and might have different object models/scales. The scale of the object model should certainly be consistent and be set appropriately for a new dataset.

**Comment by jgcbrouns** [comment]
Hello @btekin. Thank you for your answer, yet I would like to ask you to be more specific. 

The LINEMOD dataset uses ±200 images for training (while having 1200 images per class: 1000 remain for testing). How can ANY model learn from only 200 images? Aren't NNs like YOLO supposed to have thousands of images per class? 
  - My model **cannot learn anything when using 200 images** in my custom data-set; loss-functions go down (<0 for x,y loss and confidence) yet accuracy metrics stay at 0.
  - When I use **5000 images per class, accuracy maxes out at 20%** (note that I am using synthetic data)

_Sidenote: I am using lower batch-size of 8_

You speak about pre-training being necessary. Can you be more elaborate about this? **how long did you train for? How many images per class? 200 again? How many epochs**.

At this point I am distraught and about to give up...

**Comment by MohamadJaber1** [comment]
Same problem here. I raised an issue #85  mentioning that my model also is not learning. 
**And the thing is that, while validating, I can only use the first trained model which is after epoch 11. Even if my model keeps on training, it never updates the weights means that its never getting any better. It just save the summary in _costs.npz_ file** 

I used a very good source for generating my synthetic data, I have masked images too that are corresponding to my RGB images, correct intrinsics, precise labelling files, exact **diam** value and rightly scaled .ply file. I am using 1170 images with 65 different orientation of the object and different background and just using one class (object). I also previously tried the 15% training/85% testing ratio split but also didn't learn.

![SSP_revised_1](https://user-images.githubusercontent.com/48984186/56363126-c44b7880-61eb-11e9-8bf3-ce3f07fd8e08.JPG)

![SSP_fail](https://user-images.githubusercontent.com/48984186/56362433-1ab7b780-61ea-11e9-93d9-c66daac1a0af.JPG)

**After comparing my inputs with that of _ape.data_ and finding everything is matching yet not learning for custom data, I am also about to give up...**

**Comment by jgcbrouns** [comment]
Hi @MohamadJaber1 

Your green ground truth box does seem to be an incorrect bounding-box though. Maybe there still is something wrong with the labeling for your case? If you see my green ground-truth bounding boxes, they are exactly matching the object. It is indeed the case that the code is written in such a way that it will not save weights when there is no increase in accuracy. You can add a line of code to make it save weights after every 10 epochs or so. I tried this as well, but it is not helpful; if the accuracy does not increase, you can save weights all you want, but they are useless.

I have just now tried to train a model on 16.000+ images. I stopped the training at around 310 epochs, because I don't have the time to continue training this model, since I am only using a Nvidia 1080ti. Interesting enough, the loss function is pretty low, yet accuracy does not rise.

![image](https://user-images.githubusercontent.com/8687567/56413749-c44d8600-6288-11e9-8ecb-43821d80fbb6.png)

At this point I think that in general, 1000 images for training should do the trick. Because I can only use a batch-size of max 8, I think that I have to train for far more epochs than proposed in the code (700 epochs). It would be nice to hear @btekin input 😄

**Comment by MohamadJaber1** [comment]
Hi @jgcbrouns, good to hear from you and hope to hear  also from @btekin soon 😄

Thats true, even my ground truth labels aren't matching which is quite strange. I forked @juanmed _singleshotpose_ as he used the same source for generating the data I used and he also created a script called _ndds_dataset_creator.py_ that inputs your 3D bounding box configurations and output a label text file that is compatible with _singleshotpose_. You can also visualize the points (labels) at each of your images. If you can write the way you created your label files.

For saving the model, I know I can modify the script by saving whatever but as you said it is useless if the model isn't getting any better. **But my question was, why from the first place my model isn't getting any better? Why accuracy is 0?** 

By CUDA out of memory, I meant I reduced the batch size and subdivision to 4 as the _yolo-pose-pre.cfg_ was having a batch size of 32.
 
I think that the original _singleshotpose_ using LINEMOD dataset was trained over than 700 epochs in way that they kept on updating the initialization weights with the trained model and trained allover again to improve accuracy or changed the 700 epochs to any other value in thousands.

**Comment by jgcbrouns** [comment]
I also think that # epochs was way in the thousands. 


> "But my question was, why from the first place my model isn't getting any better? Why accuracy is 0?"

For your case it is pretty straightforward I think: fix the bounding box corners (check for ground truth box correctness) and your model will learn at least something (like mine). Your other settings seem to be correct: .ply file, diameter of ply vertices, camera intrinsics. Another tip: check if your .ply file has multiple vertex points. I see that your object is a lego-block. A cube in general can be modeled as a parametric 3d model. The linemod objects all have many vertices and edges in their model. @btekin uses the individual vertices to calculate accuracies against. In my hypothesis, more vertices adds more change for higher accuracy. What you could try is add more vertices in your model via blender: 

> open 3d .ply model -> select all vertices and edges -> go into edit mode -> press 'w' --> click 'subdivide'

But again, before that, fix the ground truth boundingbox label coordinates :P

**Comment by btekin** [comment]
@jgcbrouns @MohamadJabar1 Thank you for your kind feedbacks 😄

- Hello, a maximum number of 700 epochs were set for training but the model always converged much earlier than that.

- The model was trained and validated on the LINEMOD dataset. Depending on your custom data, training might proceed in a different way and might require different number of epochs, learning rates, batch sizes learning schedule etc. I would be interested in looking at your own custom synthetic datasets if you could share it to better understand what problems you are having.

- For LINEMOD, we use the standard training/test splits and apply extensive data augmentation by changing the background with segmentation masks, random scaling/translation, etc. Without using segmentation masks the accuracy might not be good enough because of the lack of generalization ability. To increase generalization, you could change the background of your images using segmentation masks or increase the number of your training samples. 

- Please also check  #84 to see if your problem comes from this. @jgcbrouns it seems that your corner predictions seem accurate, however solvepnp method of the opencv version you are using might be returning inaccurate results. Could you visualize your predictions before pnp and let me know if they are accurate?

- @MohamadJaber1 Symmetric objects with uniform texture generally brings additional challenges because of the pose ambiguity. Could you also try with non-symmetric or well textured objects and let me know how it performs.

**Comment by jgcbrouns** [comment]
hi @btekin . Thanks for your respons!

I think that the images that I posted above visualize the individual corners before PnP, straight from the predictions (red) and ground truths (green):
`    ax.scatter(corners3D[0], corners3D[1], -corners3D[2], zdir='z', c= 'red')`
`    ax.scatter(vertices[0], vertices[1], -vertices[2], zdir='z', c= 'red')`
where vertices and corners3D is:
`vertices      = np.c_[np.array(mesh.vertices), np.ones((len(mesh.vertices), 1))].transpose() `
`corners3D     = get_3D_corners(vertices)`

It would be **AWESOME** if you could take a look at my dataset!! 
I am breaking my head about this every day 😅 🔫 

Dataset: [Google Drive link](https://drive.google.com/file/d/1iHnWurJJW7Q6UDs4heJvEhiFkyROFFBN/view?usp=sharing) _~8MB, 300 images_

I will look at the ransac replacement algo for OpenCV right now.

**Comment by MohamadJaber1** [comment]
Thank you both for your replies @jgcbrouns @btekin for your reply. I will follow your comments and try them on Tuesday - Wish you both Happy Easter 😄)

@jgcbrouns Reason why I am using NDDS is that I want later to validate my model with an image taken from a robot software environment and NDDS provided me with all the necessities. 

@btekin It would be really great if you can take a look at our dataset (I will provide a sample)

**Comment by btekin** [comment]
@jgcbrouns Thank you for providing your dataset. After inspecting examples from your dataset, I would suggest you to do the two following things and see if they help:

- Reduce color data augmentation. This could be useful because your object does not have any texture and the only cue that is useful to predict the pose is color. When you apply color data augmentation (changing hue, saturation values etc.) during training, the model has difficulty in distinguishing between different colors and hence estimating the pose. You can change the values for color data augmentation at the following lines: https://github.com/Microsoft/singleshotpose/blob/master/dataset.py#L67:L69

- Randomly change the background. This could be useful as you have a small number of training examples and although you use different backgrounds for different training images, having static backgrounds for the same examples might result in overfitting. 

Hope this could help your problem. Please let me know how it goes. 

@MohamadJaber1 As @jgcbrouns pointed out, I think you would need to fix the bounding box label coordinates in order to for the model to start learning. If you provide a sample, I could also take a look at your data.

**Comment by jgcbrouns** [comment]
Hi @btekin and @MohamadJaber1 

Thank you @btekin for looking at my dataset.
Coincidentally I managed to gain some results this morning by converting my images (which are .png) to .jpg. I suspected that this could be of influence since .png can have transparent pixels in its images. Moreover I extended my tool with a mask over objects. Every object now has a mask as well. Either one of these changes fixed the problem for me.

**Comment by MohamadJaber1** [comment]
@jgcbrouns good to hear that, I will also convert the types of my images to _jpg_ later
I tried your dataset and checked the ground truth labels - they were matching fine!
![Cube_gt](https://user-images.githubusercontent.com/48984186/56590940-335c0f00-65e8-11e9-9962-5d6c71ac975a.png)
At the cmd window, I am writing
`python train.py cfg/cube.data cfg/yolo-pose.cfg backup/benchvise/init.weights`

**But the problem is that after epoch 11, the _model.weights_ is saved once and never updated. I trained the model for over than 140 epochs but even though never updated.**
![cube_training](https://user-images.githubusercontent.com/48984186/56591159-833ad600-65e8-11e9-8c48-a0c08ab5f791.JPG)

@btekin Thank you so much for offering this help.

-  [Google driver link](https://drive.google.com/drive/folders/1Wnd4levrf56NDSZvHkL1zTkkD5qVjY5C ) 400 RGB images, 400 masked images, 400 labels files, Lego.ply, test.txt, train.txt, training_range.txt (.json files from NDDS). So originally the images are **18 same pose images*****65 different orientations** = 1170 total images.

- [Lego.data](https://drive.google.com/file/d/1BR7dIaHGQ6jR110Iba9wcxzAacPXOZ3m/view?usp=sharing)

- [yolo-pose.cfg](https://drive.google.com/file/d/1lejl-9q4A2oTSrKd1cbWbTLwMKM4QoGS/view?usp=sharing)

**Please let me know what can you observe and how can I solve it**

**Comment by jgcbrouns** [comment]
Hi @MohamadJaber1  

0% acuracies after 100 epochs implies that there is something wrong for sure. The model is supposed to converge rather quickly (on average at epoch #30, the model starts showing accuracy increases. Before that, its stays at 0%).

Here is my final dataset including masks and .jpg files (converted from .png):
[Google Drive link](https://drive.google.com/open?id=1MH7DcCC6Ix86yqvmV6C6CgeTc_iFWPw_)
You can try training with this dataset. It should work 😄 

I'll take a look at your dataset now.

**Comment by jgcbrouns** [comment]
**About your quick update:**
labels are indeed ordered with a specific coordinate system in mind. Unity (where I create my dataset has a different coordinate system than blender for example). The order is important because in @btekin code, this order gets interpreted and adhered to: [link](https://github.com/Microsoft/singleshotpose/blob/master/utils.py#L65-L84)

![image](https://user-images.githubusercontent.com/8687567/56651900-5808c300-668a-11e9-99df-89cb5ac8c271.png)

You can validate if your order is correct:

1. Open your .PLY model in blender via import.
2. Your first x,y coordinate in your label file is the center, subsequently it should be the red dot as visible in the picture. This first cornercoordinate has the minimum values for x, y z. In blender you can see that this indeed matches.

**Comment by MohamadJaber1** [comment]
Hi @jgcbrouns 
Thank you for this clarification, I am so glad to know that your dataset is working with the model. This gives me hope and motivation to dig more and fix mine also :smile: 

Yea sure, it would be nice to contact you. Expect a mail soon :sunglasses: 

I am currently training on your dataset to see if it will converge with me. Also, I will go few steps backwards to check all my own custom data (mostly the labels). For the zipped version of my data, please find it here 
[Google drive link](https://drive.google.com/open?id=1kvXkjC27k2A4NZ5jYqTKPXh0ke9dTUA-) for my **1170 images**
Thank you very much

**Comment by MohamadJaber1** [comment]
Hi @jgcbrouns 
Your dataset is learning with the model pretty good :smile: 
![cube_trained_well](https://user-images.githubusercontent.com/48984186/56665416-4cc58f80-66aa-11e9-946a-6c7dcd4929bf.JPG)
This was trained for almost 60 epochs and its already showing good results :+1:

**Comment by danieldimit** [comment]
@jgcbrouns thank you for all the info you've shared in this thread. I am currently trying to figure out what's wrong with my dataset (or dataset generating tool). I am trying to learn on the dataset you've provided in this thread. After that I would try to generate the same dataset with the [tool](https://github.com/NVIDIA/Dataset_Synthesizer) I am using to see if it's working as expected.

Could you please provide the texture that you've used for your object and also if possible your data generating tool?
